image: gitpod/workspace-full-vnc
ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
tasks:
  # - init: pip3 install -r requirements.txt
  #   command: python3 game.py
  - command: python3 game.py
